version: '3.4'

services:
  bugtrackingapi:
    image: bugtrackingapi
    build:
      context: .
      dockerfile: BugTracking/Dockerfile
    ports:
      - "8080:80"
    networks:
      - my-ingress
  bugtrackingui:
    image: bugtrackingui
    build:
      context: ../CRMBug-FE
      dockerfile: DockerFile
    ports:
      - "9090:3000"
    networks:
      - my-ingress
  databasemysql:
    image: mysqldb
    build:
      context: ../DataBase
      dockerfile: DockerFile
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345678@Abc
    ports:
      - "3306:3306"
    networks:
      - my-ingress
networks:
  my-ingress:
    attachable: true
    external: true
