# Base image
# FROM node:lts-alpine as build


# COPY package.json /app/package.json
# RUN npm install

# COPY . /app

# RUN npm run build

FROM nginx:alpine


# Working directory
WORKDIR /app

COPY /dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]